spring:
  application:
    name: tickets

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: x3akqrtww

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: tickets
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  servlet:
    context-path: /api/v1